ufc:
  target: dev
  outputs:
    dev:
      type: postgres
      host: 127.0.0.1
      user: postgres
      password: postgres
      port: 5432
      dbname: ufc
      schema: fighters_extracted
      sslmode: disable
