version: 2

sources:
  - name: ufc
    schema: ufc
    tables:
      - name: dim_ufc_event_details
      - name: fact_ufc_fight_details
      - name: fact_ufc_fight_results
      - name: fact_ufc_fight_stats
      - name: dim_ufc_fighter_details
      - name: dim_ufc_fighter_tott
